config/routes.rb
Rails
  .application
  .routes
  .draw do
    namespace :api do
      resources :users
      resources :contacts
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      post '/auth_conf', to: 'sessions#auth_conf'
    end
    root 'page#index'
    get '*path', to: 'page#index'
    # resources :questions, only: [:show,:new,:create, :destroy]
  end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    <div class="copy-right-container">©︎ 2020 Please Teach Me, All rights reserved</div>
    <div class="sns-container">
      <div>管理人 SNS</div>
      <ul>
        <li>
          <%= link_to '#' do %>
            <i class="fab fa-twitter sns-icon"></i>
          <% end %>   
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fab fa-facebook-f sns-icon"></i>
          <% end %>   
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fab fa-github sns-icon"></i>
          <% end %>   
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-wrapper">
    <div class="app-logo-container">
      <%= link_to embedded_svg("PLEASE TEACH ME LOGO.svg",
      class: "application-logo",alt: "PleaseTeachMe logo",
      width:"200px"), root_path %>
    </div>
    <nav>
      <div class="nav-container">
          <div class="static-pages-nav">
            <ul class="nav">
              <li><%= link_to 'ヘルプ', static_pages_help_path %></li>
              <li><%= link_to 'お問合せ', new_contact_path %></li>
            </ul>
          </div>
          <div class="user-nav-wrapper">
            <button id="user-nav-button" type="button">
              <div>
                <%= image_tag("user-menu-logo",class: "user-menu-logo")%>
              </div>
            </button>
            <div class="user-nav" id="user-nav">
              <ul>
                <%if logged_in? %>
                  <li><%= link_to "ログアウト" , logout_path, method: :delete %></li>
                  <li><%= link_to "マイページ" , user_path(current_user) %></li>
                  <li><%= link_to "登録内容編集", edit_user_path(current_user) %></li>
                <% else %>
                <li><%= link_to '登録する', new_user_path , class: "signup-btn"%></li>
                  <li><%= link_to "ログイン", login_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %> |Please Teach Me</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'hello_vue' %>
  <%= javascript_pack_tag 'hello_vue' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="app">
    <%= yield%>
  </div>
</body>

</html>